"""
Classes and functions for loading two-photon imaging data.

For loading stim sync file see:
/home/sjara/src/jarapubs/2020nsf/figure_twocell_scatter.py
"""

import os
from typing import Any, Dict, Optional
import numpy as np
import scipy.io

def load_suite2p_data(data_path):
    """
    Load Suite2P processed data from a specified directory.
    
    This function loads the standard output files generated by Suite2P, including
    fluorescence traces, deconvolved spikes, ROI statistics, and cell classification.
    For more details on Suite2P outputs, see:
    https://suite2p.readthedocs.io/en/latest/outputs.html

    Args:
        data_path (str): Path to the directory containing Suite2P output files.
            Expected format: 'subject_processed/YYYYMMDD/session/suite2p/planeN/'
            Example: 'imag022_processed/20260123/012/suite2p/plane0/'
    
    Returns:
        tuple: A 6-element tuple containing:
            roiF (numpy.ndarray): Fluorescence traces, shape (n_ROIs, n_timepoints).
                Loaded from 'F.npy'.
            neuropilF (numpy.ndarray): Neuropil fluorescence traces, shape (n_ROIs, n_timepoints).
                Loaded from 'Fneu.npy'.
            spks (numpy.ndarray): Deconvolved spike traces, shape (n_ROIs, n_timepoints).
                Loaded from 'spks.npy'.
            stat (numpy.ndarray): Array of dictionaries containing ROI statistics.
                Each element contains properties like coordinates, compactness, etc.
                Loaded from 'stat.npy'.
            ops (dict): Suite2P operations/parameters dictionary.
                Contains processing parameters and metadata like sampling rate ('fs').
                Loaded from 'ops.npy'.
            iscell (numpy.ndarray): Cell classification array, shape (n_ROIs, 2).
                Column 0: Binary classification (0=not cell, 1=cell).
                Column 1: Probability that the ROI is a cell (0-1).
                Loaded from 'iscell.npy'.
    
    Example:
        >>> data_path = '/path/to/suite2p/plane0/'
        >>> roiF, neuropilF, spks, stat, ops, iscell = load_suite2p_data(data_path)
        >>> print(f"Loaded {roiF.shape[0]} ROIs with {roiF.shape[1]} timepoints")
        >>> print(f"Sampling rate: {ops['fs']} Hz")
    """
    # -- Load the calcium imaging data --
    roiF = np.load(os.path.join(data_path, 'F.npy'), allow_pickle=True)
    neuropilF = np.load(os.path.join(data_path, 'Fneu.npy'), allow_pickle=True)
    spks = np.load(os.path.join(data_path, 'spks.npy'), allow_pickle=True)
    stat = np.load(os.path.join(data_path, 'stat.npy'), allow_pickle=True)
    ops = np.load(os.path.join(data_path, 'ops.npy'), allow_pickle=True).item()
    iscell = np.load(os.path.join(data_path, 'iscell.npy'), allow_pickle=True)
    return (roiF, neuropilF, spks, stat, ops, iscell)


def load_scanbox_mat_file(filepath):
    """
    Load .mat file created by ScanBox containing stimulus sync data.
    
    This function loads the ScanBox info structure from a .mat file and converts
    MATLAB structures to nested Python dictionaries.
    Based on https://scanbox.org/2016/09/02/reading-scanbox-files-in-python/

    Args:
        filepath (str): Path to the .mat file containing stimulus sync data.
            Expected format: 'SUBJECT_processed/YYYYMMDD/session/SUBJECT_YYMMDD_session.mat'
    
    Returns:
        dict: ScanBox info structure containing imaging metadata and stimulus sync information.
            Key fields include:
            - 'config': Configuration parameters (e.g., lines per frame)
            - 'frame': Frame numbers for stimulus events
            - 'line': Line numbers within frames for stimulus events
            - 'event_id': IDs of stimulus events
    
    Example:
        >>> filepath = 'imag022_processed/20260123/012/imag022_20260123_012.mat'
        >>> sbxinfo = load_scanbox_mat_file(filepath)
        >>> lines_per_frame = sbxinfo['config']['lines']
    """
    # sync_data = io.loadmat(file_path)
    # idata = sync_data['info'][0][0]
    # return idata['frames'][0][0]
    data = scipy.io.loadmat(filepath, struct_as_record=False, squeeze_me=True)
    sbxinfo = _check_keys(data)['info']
    return sbxinfo
 
def _check_keys(dict):
    '''
    Checks if entries in dictionary are mat-objects. If yes
    todict is called to change them to nested dictionaries
    Based on https://scanbox.org/2016/09/02/reading-scanbox-files-in-python/
    '''
    for key in dict:
        if isinstance(dict[key], scipy.io.matlab.mat_struct):
            dict[key] = _todict(dict[key])
    return dict
 
def _todict(matobj):
    '''
    A recursive function which constructs from matobjects nested dictionaries
    Based on https://scanbox.org/2016/09/02/reading-scanbox-files-in-python/
    '''
    dict = {}
    for strg in matobj._fieldnames:
        elem = matobj.__dict__[strg]
        if isinstance(elem, scipy.io.matlab.mat_struct):
            dict[strg] = _todict(elem)
        else:
            dict[strg] = elem
    return dict

def get_event_onset(sbxinfo):
    """
    Extract event/stimulus onset times from ScanBox info structure.
    
    This function calculates the precise onset frame for each stimulus event by
    combining frame and line information. Only onset events (even indices) are
    extracted, as ScanBox records both onset and offset times.

    Args:
        sbxinfo (dict): ScanBox info structure loaded from .mat file.
            Must contain 'config', 'frame', 'line', and 'event_id' fields.
    
    Returns:
        tuple: A 2-element tuple containing:
            event_onset_frame (numpy.ndarray): Array of stimulus onset times in frame units.
                Fractional values indicate sub-frame timing based on scan line.
            event_id (numpy.ndarray): Array of event IDs corresponding to each onset.
    
    Example:
        >>> sbxinfo = load_scanbox_mat_file('imag022_20260123_012.mat')
        >>> event_onset, event_id = get_event_onset(sbxinfo)
        >>> # Convert to seconds: event_onset_sec = event_onset / frame_rate
    """
    lines_per_frame = sbxinfo['config']['lines']
    onset_frame = sbxinfo['frame'][::2]-1  # Even indices are onsets (convert to 0-based)
    onset_line = sbxinfo['line'][::2]-1  # Even indices are onsets (convert to 0-based)
    event_onset_frame = onset_frame + (onset_line / lines_per_frame)
    event_id = sbxinfo['event_id'][::2]
    return event_onset_frame, event_id


class SbxReader:
    """Reader for .sbx files produced by the original MATLAB Scanbox.

    This class was copied from pyscanbox.io.sbx_reader import SbxReader.
    
    Scanbox stores raw uint16 data in MATLAB column-major (Fortran) order.
    The on-disk layout per frame is equivalent to the C-order shape
    ``(lines_per_frame, pixels_per_line, nchan)``.  Values are stored as
    their bitwise complement (``stored = 65535 - signal``); this class
    undoes that automatically in ``get_frame()`` and ``get_channel()``.

    The companion .mat file contains a nested MATLAB struct named ``info``
    with fields including:

    * ``sz``  – ``[lines_per_frame, pixels_per_line]``
    * ``recordsPerBuffer``  – lines per frame (same as ``sz[0]``)
    * ``channels``  – PMT channel bitmask:
        * ``1`` → both PMT0 & PMT1 (nchan = 2)
        * ``2`` → PMT0 only  (nchan = 1)
        * ``3`` → PMT1 only  (nchan = 1)
    * ``scanbox_version``  – file format version (>= 2 for modern files)
    * ``scanmode``  – ``0`` = bidirectional, ``1`` = unidirectional

    The number of frames is derived from the file size rather than any
    metadata field because Scanbox truncates the field on premature stop.

    Reference implementation: ``Scanbox/sbx/sbxread.m``

    Attributes:
        filepath: Base path (without extension).
        sbx_path: Full path to the .sbx binary file.
        mat_path: Full path to the .mat metadata file.
        info: Flattened dictionary of the ``info`` struct fields.
        data: Memory-mapped numpy array, shape
            ``(nframes, lines_per_frame, pixels_per_line, nchan)``.
            This is the raw (bitwise-complemented) layout as stored on
            disk.  Use ``get_frame()`` / ``get_channel()`` to obtain
            processed data in the standard
            ``(nchan, lines_per_frame, pixels_per_line)`` orientation.
    """

    # Mapping from .mat ``channels`` field value to number of active PMT channels.
    _CHANNELS_TO_NCHAN = {1: 2, 2: 1, 3: 1}

    def __init__(self, filepath: str):
        """Initialize the original Scanbox .sbx reader.

        Args:
            filepath: Base path without extension (e.g., 'mydata').
                Will load 'mydata.sbx' and 'mydata.mat'.

        Raises:
            FileNotFoundError: If .sbx or .mat file does not exist.
            KeyError: If the .mat file does not contain the ``info`` struct.
            ValueError: If ``channels`` field has an unexpected value.
        """
        self.filepath = filepath
        self.sbx_path = f"{filepath}.sbx"
        self.mat_path = f"{filepath}.mat"
        self._mmap: Optional[np.memmap] = None

        if not os.path.exists(self.sbx_path):
            raise FileNotFoundError(f".sbx file not found: {self.sbx_path}")
        if not os.path.exists(self.mat_path):
            raise FileNotFoundError(f".mat file not found: {self.mat_path}")

        self.info = self._load_info()
        self.data = self._open_sbx()

    # ------------------------------------------------------------------
    # Properties
    # ------------------------------------------------------------------

    @property
    def shape(self):
        """Memory-map shape: (nframes, lines_per_frame, pixels_per_line, nchan)."""
        return self.data.shape

    @property
    def num_frames(self) -> int:
        """Number of frames derived from file size."""
        return self.data.shape[0]

    @property
    def num_channels(self) -> int:
        """Number of active PMT channels (1 or 2)."""
        return int(self.info['nchan'])

    @property
    def lines_per_frame(self) -> int:
        """Number of scan lines per frame."""
        return int(self.info['sz'][0])

    @property
    def pixels_per_line(self) -> int:
        """Number of pixels per scan line."""
        return int(self.info['sz'][1])

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _load_info(self) -> Dict[str, Any]:
        """Load and flatten the ``info`` struct from the .mat file.

        Scanbox saves a MATLAB struct named ``info`` into the .mat file.
        ``scipy.io.loadmat`` returns it as a structured numpy array;
        this method unwraps all scalar fields to plain Python scalars.

        Returns:
            Flat dictionary of ``info`` struct fields plus a computed
            ``nchan`` key.

        Raises:
            KeyError: If ``info`` key is absent from the .mat file.
            ValueError: If ``channels`` encodes an unknown PMT configuration.
        """
        raw = scipy.io.loadmat(self.mat_path, squeeze_me=True,
                               struct_as_record=False)
        if 'info' not in raw:
            raise KeyError(
                f"No 'info' struct found in {self.mat_path}. "
                "This file may have been written by the old pyscanbox native "
                "format — use SbxReader instead."
            )

        info_obj = raw['info']  # scipy MatlabObject or structured array
        # Convert to a plain dict by iterating over _fieldnames
        flat: Dict[str, Any] = {}
        for field in info_obj._fieldnames:
            val = getattr(info_obj, field)
            flat[field] = val

        # Derive nchan from the channels bitmask
        channels = int(flat['channels'])
        if channels not in self._CHANNELS_TO_NCHAN:
            raise ValueError(
                f"Unexpected 'channels' value {channels} in {self.mat_path}. "
                f"Expected one of {list(self._CHANNELS_TO_NCHAN)}: "
                "1=both PMTs, 2=PMT0, 3=PMT1."
            )
        flat['nchan'] = self._CHANNELS_TO_NCHAN[channels]

        return flat

    def _open_sbx(self) -> np.memmap:
        """Memory-map the .sbx binary file.

        Scanbox writes data in MATLAB column-major order.  For each frame
        the fastest-varying index is the channel, then pixel, then line.
        Expressed as a C-order numpy shape this is
        ``(lines_per_frame, pixels_per_line, nchan)`` per frame.

        The number of frames is computed solely from the file size so that
        recordings stopped early are handled correctly.

        Returns:
            numpy.memmap with C-order shape
            ``(nframes, lines_per_frame, pixels_per_line, nchan)``.

        Raises:
            ValueError: If the file size is not an exact multiple of one
                frame's worth of bytes.
        """
        nchan = int(self.info['nchan'])
        sz = self.info['sz']          # [lines, pixels]
        lines = int(sz[0])
        pixels = int(sz[1])

        bytes_per_frame = nchan * lines * pixels * np.dtype(np.uint16).itemsize
        file_bytes = os.path.getsize(self.sbx_path)

        if file_bytes % bytes_per_frame != 0:
            raise ValueError(
                f"File size {file_bytes} bytes is not divisible by the "
                f"expected frame size {bytes_per_frame} bytes "
                f"({nchan} ch × {lines} lines × {pixels} px × 2 bytes)."
            )

        nframes = file_bytes // bytes_per_frame
        # C-order shape that matches MATLAB Fortran-order (nchan, pixels, lines)
        shape = (nframes, lines, pixels, nchan)
        self._mmap = np.memmap(self.sbx_path, dtype=np.uint16, mode='r',
                               shape=shape)
        return self._mmap

    # ------------------------------------------------------------------
    # Public access methods
    # ------------------------------------------------------------------

    def get_frame(self, index: int, invert: bool = True) -> np.ndarray:
        """Return a single frame as a numpy array.

        Args:
            index: Frame index (0-based).
            invert: If ``True`` (default), apply ``65535 − stored`` and
                return **signal convention** (high = bright fluorescence,
                low = dark background), matching ``sbxread.m`` and
                downstream tools such as Suite2p.  If ``False``, return
                the raw on-disk values in **wire-format convention**
                (high = dark) — use this when feeding the GUI display
                pipeline, which applies its own inversion internally.

        Returns:
            Array of shape ``(nchan, lines_per_frame, pixels_per_line)``,
            dtype uint16.

        Raises:
            IndexError: If index is out of range.
        """
        if index < 0 or index >= self.num_frames:
            raise IndexError(
                f"Frame index {index} out of range [0, {self.num_frames - 1}]"
            )
        # Disk layout per frame (C-order): (lines, pixels, nchan)
        # Transpose to (nchan, lines, pixels) to match MATLAB permute([1 3 2])
        frame = np.array(self.data[index]).transpose(2, 0, 1)
        if invert:
            return np.uint16(65535) - frame
        return frame

    def get_channel(self, channel: int, invert: bool = True) -> np.ndarray:
        """Return all frames for a single PMT channel.

        Args:
            channel: Channel index (0-based).
            invert: If ``True`` (default), apply ``65535 − stored`` to
                return signal convention (high = bright).  If ``False``,
                return wire-format values (high = dark) as stored on disk.

        Returns:
            Array of shape ``(nframes, lines_per_frame, pixels_per_line)``,
            dtype uint16.

        Raises:
            IndexError: If channel index is out of range.
        """
        if channel < 0 or channel >= self.num_channels:
            raise IndexError(
                f"Channel index {channel} out of range "
                f"[0, {self.num_channels - 1}]"
            )
        # data shape: (nframes, lines, pixels, nchan) → select channel last axis
        ch_data = np.array(self.data[:, :, :, channel])
        if invert:
            return np.uint16(65535) - ch_data
        return ch_data

    def load(self, invert: bool = True) -> np.ndarray:
        """Load the entire dataset into memory.

        Args:
            invert: If ``True`` (default), apply ``65535 − stored`` to
                return signal convention (high = bright), matching
                ``sbxread.m``.  If ``False``, return wire-format values
                (high = dark) as stored on disk.

        Returns:
            Array of shape
            ``(nframes, nchan, lines_per_frame, pixels_per_line)``,
            dtype uint16.

        Note:
            For large files this may consume significant RAM.  Prefer
            ``get_frame()`` or ``get_channel()`` for selective access.
        """
        # data shape on disk: (nframes, lines, pixels, nchan)
        # Desired output:     (nframes, nchan, lines, pixels)
        result = np.array(self.data).transpose(0, 3, 1, 2)
        if invert:
            return np.uint16(65535) - result
        return result

    def close(self) -> None:
        """Release the memory-mapped file handle."""
        if self._mmap is not None:
            del self._mmap
            self._mmap = None
            self.data = None

    def __enter__(self):
        """Context manager entry."""
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        """Context manager exit."""
        self.close()

    def __repr__(self) -> str:
        return (
            f"SbxReader('{self.filepath}', "
            f"nframes={self.num_frames}, nchan={self.num_channels}, "
            f"lines={self.lines_per_frame}, pixels={self.pixels_per_line})"
        )



if __name__ == "__main__":
    filepath = '/data/twophoton/imag022_processed/20260123/012/imag022_20260123_012.mat'
    sbxinfo = load_scanbox_mat_file(filepath)
    event_onset, event_id = get_event_onset(sbxinfo)
