"""
Classes and functions for loading two-photon imaging data.

For loading stim sync file see:
/home/sjara/src/jarapubs/2020nsf/figure_twocell_scatter.py
"""

import os
import numpy as np
import scipy.io as spio

def load_suite2p_data(data_path):
    """
    Load Suite2P processed data from a specified directory.
    
    This function loads the standard output files generated by Suite2P, including
    fluorescence traces, deconvolved spikes, ROI statistics, and cell classification.
    For more details on Suite2P outputs, see:
    https://suite2p.readthedocs.io/en/latest/outputs.html

    Args:
        data_path (str): Path to the directory containing Suite2P output files.
            Expected format: 'subject_processed/YYYYMMDD/session/suite2p/planeN/'
            Example: 'imag022_processed/20260123/012/suite2p/plane0/'
    
    Returns:
        tuple: A 6-element tuple containing:
            roiF (numpy.ndarray): Fluorescence traces, shape (n_ROIs, n_timepoints).
                Loaded from 'F.npy'.
            neuropilF (numpy.ndarray): Neuropil fluorescence traces, shape (n_ROIs, n_timepoints).
                Loaded from 'Fneu.npy'.
            spks (numpy.ndarray): Deconvolved spike traces, shape (n_ROIs, n_timepoints).
                Loaded from 'spks.npy'.
            stat (numpy.ndarray): Array of dictionaries containing ROI statistics.
                Each element contains properties like coordinates, compactness, etc.
                Loaded from 'stat.npy'.
            ops (dict): Suite2P operations/parameters dictionary.
                Contains processing parameters and metadata like sampling rate ('fs').
                Loaded from 'ops.npy'.
            iscell (numpy.ndarray): Cell classification array, shape (n_ROIs, 2).
                Column 0: Binary classification (0=not cell, 1=cell).
                Column 1: Probability that the ROI is a cell (0-1).
                Loaded from 'iscell.npy'.
    
    Example:
        >>> data_path = '/path/to/suite2p/plane0/'
        >>> roiF, neuropilF, spks, stat, ops, iscell = load_suite2p_data(data_path)
        >>> print(f"Loaded {roiF.shape[0]} ROIs with {roiF.shape[1]} timepoints")
        >>> print(f"Sampling rate: {ops['fs']} Hz")
    """
    # -- Load the calcium imaging data --
    roiF = np.load(os.path.join(data_path, 'F.npy'), allow_pickle=True)
    neuropilF = np.load(os.path.join(data_path, 'Fneu.npy'), allow_pickle=True)
    spks = np.load(os.path.join(data_path, 'spks.npy'), allow_pickle=True)
    stat = np.load(os.path.join(data_path, 'stat.npy'), allow_pickle=True)
    ops = np.load(os.path.join(data_path, 'ops.npy'), allow_pickle=True).item()
    iscell = np.load(os.path.join(data_path, 'iscell.npy'), allow_pickle=True)
    return (roiF, neuropilF, spks, stat, ops, iscell)


def load_scanbox_mat_file(filepath):
    """
    Load .mat file created by ScanBox containing stimulus sync data.
    
    This function loads the ScanBox info structure from a .mat file and converts
    MATLAB structures to nested Python dictionaries.
    Based on https://scanbox.org/2016/09/02/reading-scanbox-files-in-python/

    Args:
        filepath (str): Path to the .mat file containing stimulus sync data.
            Expected format: 'SUBJECT_processed/YYYYMMDD/session/SUBJECT_YYMMDD_session.mat'
    
    Returns:
        dict: ScanBox info structure containing imaging metadata and stimulus sync information.
            Key fields include:
            - 'config': Configuration parameters (e.g., lines per frame)
            - 'frame': Frame numbers for stimulus events
            - 'line': Line numbers within frames for stimulus events
            - 'event_id': IDs of stimulus events
    
    Example:
        >>> filepath = 'imag022_processed/20260123/012/imag022_20260123_012.mat'
        >>> sbxinfo = load_scanbox_mat_file(filepath)
        >>> lines_per_frame = sbxinfo['config']['lines']
    """
    # sync_data = io.loadmat(file_path)
    # idata = sync_data['info'][0][0]
    # return idata['frames'][0][0]
    data = spio.loadmat(filepath, struct_as_record=False, squeeze_me=True)
    sbxinfo = _check_keys(data)['info']
    return sbxinfo
 
def _check_keys(dict):
    '''
    Checks if entries in dictionary are mat-objects. If yes
    todict is called to change them to nested dictionaries
    Based on https://scanbox.org/2016/09/02/reading-scanbox-files-in-python/
    '''
    for key in dict:
        if isinstance(dict[key], spio.matlab.mat_struct):
            dict[key] = _todict(dict[key])
    return dict
 
def _todict(matobj):
    '''
    A recursive function which constructs from matobjects nested dictionaries
    Based on https://scanbox.org/2016/09/02/reading-scanbox-files-in-python/
    '''
    dict = {}
    for strg in matobj._fieldnames:
        elem = matobj.__dict__[strg]
        if isinstance(elem, spio.matlab.mat_struct):
            dict[strg] = _todict(elem)
        else:
            dict[strg] = elem
    return dict

def get_event_onset(sbxinfo):
    """
    Extract event/stimulus onset times from ScanBox info structure.
    
    This function calculates the precise onset frame for each stimulus event by
    combining frame and line information. Only onset events (even indices) are
    extracted, as ScanBox records both onset and offset times.

    Args:
        sbxinfo (dict): ScanBox info structure loaded from .mat file.
            Must contain 'config', 'frame', 'line', and 'event_id' fields.
    
    Returns:
        tuple: A 2-element tuple containing:
            event_onset_frame (numpy.ndarray): Array of stimulus onset times in frame units.
                Fractional values indicate sub-frame timing based on scan line.
            event_id (numpy.ndarray): Array of event IDs corresponding to each onset.
    
    Example:
        >>> sbxinfo = load_scanbox_mat_file('imag022_20260123_012.mat')
        >>> event_onset, event_id = get_event_onset(sbxinfo)
        >>> # Convert to seconds: event_onset_sec = event_onset / frame_rate
    """
    lines_per_frame = sbxinfo['config']['lines']
    onset_frame = sbxinfo['frame'][::2]-1  # Even indices are onsets (convert to 0-based)
    onset_line = sbxinfo['line'][::2]-1  # Even indices are onsets (convert to 0-based)
    event_onset_frame = onset_frame + (onset_line / lines_per_frame)
    event_id = sbxinfo['event_id'][::2]
    return event_onset_frame, event_id



if __name__ == "__main__":
    filepath = '/data/twophoton/imag022_processed/20260123/012/imag022_20260123_012.mat'
    sbxinfo = load_scanbox_mat_file(filepath)
    event_onset, event_id = get_event_onset(sbxinfo)
